[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
type = "HTTP"
path = "/api/health"
interval = 30
timeout = 10
retries = 3 